### ISSUE TITLE
null 2024 Global Committee Election Call for Questions

### ISSUE THREAD

**Issue by pankajmouriya** [null-open-security-community/null-Global-Committee-Call-For-Questions#1]
Please use this GitHub issue to post questions you'd like to ask candidates running for the Null committee. Post each question as a separate comment, so they can be individually upvoted by clicking the 'thumbs up' icon. This call for questions opens on September 9th, 2024, and closes on September 30th, 2024. Your participation will help us select the best leaders for our community.

**Comment by pankajmouriya** [comment]
Q: How will you encourage the community to start, lead, and grow new null initiatives, projects and chapters?

**Comment by anantshri** [comment]
Q: How do you see null flourishing in next 10 years, and going beyond the usual chapter creation and meetup flow?

Context: The community has been following a linear path (open chapters, do meetings, do live events, rinse repeat), there have been some attempts at projects (jobs, keeda, a few other project) but very few survive or thrive.

**Comment by Yuvvi01** [comment]
Q: Many of the NULL chapters are dead or inactive. When the chapter leaders are contacted, they don’t respond. What can be done if someone is willing to take initiative but is restricted due to the lack of a proper platform or support?

**Comment by rohitcoder** [comment]
Q: What happened to "Kriya" ? I guess it never happened in Bangalore or chapter or what? I was waiting or that from long time, can we have some other cool sessions / hackathons sometimes quarterly / yearly, instead of just having talks/workshops?

**Comment by s3curitydojolab** [comment]
Q: There has been a noticeable increase in community competition during recent period and also the quality of the content is also decreasing. How committee is planing to address these challenges considering that content quality directly impacts the learning & overall growth of the community?

**Comment by AbdulRasheed2020** [comment]
Question: From an open security community perspective, in addition to our current resources, how will you, as a board member, contribute to ensuring that the evolving needs of both beginners and experts are met while maintaining consistency and accessibility of knowledge and resources globally as the community decentralizes into regional chapters?

**Comment by samsbp** [comment]
Q: When compared with OWASP. OWASP has better projects that are used in the industry. Why Null is not able to produce any good projects that are used? is it because of sponsorship issues or do we not have it in our vision? 
Q: What is the vision of null? why cannot see it on our main page?

**Comment by 0xbharath** [comment]
Q: Do you have plans to ensure that "the limitations/bias of leadership doesn't limit/bias the community"? 

Context: In my personal observation, I noticed that chapters are being limited or skewed towards a specific direction because of the limitations of the leads. 

By limitations, I mean, technical domain of the leads, leads view of infosec etc.
By bias, I mean, the personal opinion of what is important & what's not important for community etc.

**Comment by 0xbharath** [comment]
Q: Do you have plans for Null to collaborate with other open communities like [FOSS United](https://fossunited.org/) etc to foster cross-community collaboration?

**Comment by sanjay7178** [comment]
Q : Do Null  have plans to take part in Google Summer of Code to maintain and create projects like owasp does every year ?  
 
reference :  https://owasp.org/www-community/initiatives/gsoc/

**Comment by anantshri** [comment]
Q: What has been your contribution so far in Null community? In terms of organisational activity?

Context: I would prefer to vote for someone who is actively contributing to the community and not solely aiming for designation.

**Comment by samcneill** [comment]
What is the committe's governance and policy framework? Sure you can do one for worldwide, but there are chapters.

**Comment by cypher-28** [comment]
The main purpose of these community meetups and talks are about knowledge sharing and meeting with people. The meeting with people/Networking part is going good but the KNOWLEDGE SHARING part is not that good.
Context: there is a variety of audience which come to attend meetups maybe the people who have many years of experience may understand things but people who are new may not work for them.

So How will you take into account and resolve this problem?

**Comment by hehacks** [comment]
Q: How do you envision fostering a more self-sufficient and innovative Null community, where members are empowered to start and sustain their own initiatives, projects, and chapters, get jobs,  rather than solely relying on top-down guidance all the time?

**Comment by hehacks** [comment]
As Null continues to decentralize and expand globally, how will you ensure the long-term sustainability and relevance of the community and how do you track the all the regional chapters to have equally active participation?

**Comment by pankajmouriya** [comment]
The final list of questions are available in #3
